# Generated by Django 6.0.7 on 2026-08-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contrato_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefone',
            new_name='celular',
        ),
    ]
